#!/bin/sh

usage="usage: ${0##*/} PACKAGE_NAME"

case "$#,$1" in
1,-*)
	echo $usage 1>&2
	;;
1,*)
	dh_make --packagename ${1}_0 --yes --native --defaultless \
		--templates /usr/share/devscripts-ptux/ptuxmake/templates-native-gpl3 
	mkdir debian/source
	echo "3.0 (native)" >debian/source/format
	;;
*)
	echo $usage 1>&2
	;;
esac
